const app = document.querySelector('#app')
const header = document.querySelector('header')
const section = document.querySelector('#sidebar')
const main = document.querySelector('main')
const hero = document.querySelector('#hero')
const price = document.querySelector('#price')
const box1 = document.querySelector('#box1')
